fix ICP replicas reconciliation
banzaicloud/istio-operator pull request #853
Opened 2022-06-09 09:59 UTC by LuciferInLove

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | 
| License         | Apache 2.0

### What's in this PR?
Fixed a bug where the istiod number of replicas couldn't be changed in the IstioControlPlane resource.

2022-06-09 10:38 UTC, kristofgyuracz approved these changes
LGTM

2022-06-09 11:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/banzaicloud/istio-operator?pullRequest=853) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/banzaicloud/istio-operator?pullRequest=853) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/banzaicloud/istio-operator?pullRequest=853) it.</sub>

2022-06-14 21:31 UTC, waynz0r requested changes
@LuciferInLove,

in its current state this doesn't really solves the base problem. Although the replica count is set for the deployment it will be overridden by the HPA since the autoscale is still enabled by default.

After internal discussion the expected behaviour for the CR fields are the following:

- there is a 1-5 autoscale enabled by default
- if only the `count` is set then the autoscale should be disabled and the count is set for the deployment
- `min` or `max` has precedence, if either one of those  is set (regardless of the value of the `count` if any) then those override the default setting and the autoscale is enabled accordingly
- the actual count always >= `min` and is always set for the deployment

```
# autoscale disabled, fixed replica count is set for the deployment
replicas:
  count: 4
```

```
# autoscale enabled (2-5), count = 2
replicas:
  min: 2
```

```
# autoscale enabled (2-4), count = 3
replicas:
  count: 3
  min: 2
  max: 4
```

2022-06-21 09:27 UTC, waynz0r approved these changes

2022-06-21 10:53 UTC, merged