Bump versions for new tags
banzaicloud/istio-operator pull request #870
Opened 2022-10-12 12:22 UTC by Kuvesz

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| License         | Apache 2.0

### What's in this PR?
Forgot to bump up the versions so I can create new tags. Sorry about he double PR.

### Why?
Same as above.

### Checklist

- [X] Implementation tested
- [X] Error handling code meets the [guideline](https://github.com/banzaicloud/pipeline/blob/master/docs/error-handling-guide.md)
- [X] Logging code meets the guideline

2022-10-12 12:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/banzaicloud/istio-operator?pullRequest=870) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/banzaicloud/istio-operator?pullRequest=870) before we can accept your contribution.<br/><hr/>**kovacs.david1101@gmail.com** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/banzaicloud/istio-operator?pullRequest=870) it.</sub>

2022-10-12 12:46 UTC, pregnor reviewed
LGTM

2022-10-12 13:42 UTC, Laci21 requested changes

2022-10-12 13:42 UTC, Laci21 commented on deploy/charts/istio-operator/Chart.yaml
> +appVersion: "v2.16.0"
```suggestion
appVersion: "v2.15.1"
```

We have an unwritten convention that the appVersion's minor version should be the same as Istio's minor version. E.g. for Istio 1.15, we should have `v2.15.x` appVersions. (We already have `v2.15.0` released, that's why I'm suggesting `v2.15.1`.)

Also, we want to write down this convention to the docs, sorry about this.

(Btw I see these versions tagged already `v2.16.0`, `deploy/charts/v2.0.17`, `chart/istio-operator/2.0.17` and `api/v2.16.0`, even though this PR is not merged yet. I don't know why that's the case, but they shouldn't be tagged like that without merging the corresponsing PR.)

2022-10-12 13:47 UTC, pregnor commented on deploy/charts/istio-operator/Chart.yaml
> +appVersion: "v2.16.0"
IMO we should document this

2022-10-12 13:48 UTC, Laci21 commented on deploy/charts/istio-operator/Chart.yaml
> +appVersion: "v2.16.0"
Yes, agreed. - "Also, we want to write down this convention to the docs, sorry about this."

2022-10-12 13:49 UTC, Kuvesz commented on deploy/charts/istio-operator/Chart.yaml
> +appVersion: "v2.16.0"
Okay, I'll change it. Also I just realized that I forgot these when I created the tags, I'll get rid of those

2022-10-12 14:59 UTC, Laci21 approved these changes

2022-10-13 10:08 UTC, bartam1 approved these changes

2022-10-13 10:09 UTC, merged